[package]
name = "AI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.18"
ethcontract = "0.13"
ethcontract-generate = "0.23.0"

